[package]
name = "verseapp"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13", features = ["image", "tokio", "svg"] }
rfd = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "sync", "time", "macros"] }
dirs = "5.0"
zip = { version = "2.1", default-features = false, features = ["deflate"] }
mupdf = "0.8"
djvu = "0.1.0"
rdocx = "0.1"

[profile.release]
opt-level = "s"     # Optimize for size ("z" or "s") instead of speed
lto = true          # Link-Time Optimization (removes unused code across crates)
codegen-units = 1   # Reduces parallel code units to allow better size optimizations
panic = "abort"     # Removes stack unwinding code when a panic occurs
strip = true        # Automatically strips debug symbols from the executable